# Generated by Django 4.2 on 2024-04-11 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='create_date',
        ),
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 11, 20, 42, 41, 336606, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 20, 42, 41, 337603, tzinfo=datetime.timezone.utc)),
        ),
    ]
