# Generated by Django 4.2 on 2024-07-06 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_comment_create_date_comment_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 4, 52, 43, 391415, tzinfo=datetime.timezone.utc)),
        ),
    ]
