# Generated by Django 4.2 on 2024-07-06 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 5, 19, 5, 556653, tzinfo=datetime.timezone.utc)),
        ),
    ]
